// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6i8UnGGb7w3CImt_AkCxFLPzUtAkXazg',
    appId: '1:682632352793:android:466b5fb563db5e3d52c688',
    messagingSenderId: '682632352793',
    projectId: 'fir-project-kelompok',
    storageBucket: 'fir-project-kelompok.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0HCfHdntb_xjdlLNilW0e-cWTu0rSkSM',
    appId: '1:682632352793:ios:26dc766829521f1352c688',
    messagingSenderId: '682632352793',
    projectId: 'fir-project-kelompok',
    storageBucket: 'fir-project-kelompok.firebasestorage.app',
    androidClientId: '682632352793-3hcj26kuetmum917h6n4km5mopmhtlql.apps.googleusercontent.com',
    iosClientId: '682632352793-r92dnuutusa9jfvgql6nan6d1k7d4e6v.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseProject',
  );
}
